---
title: "Esplaining roe deer movement in the Italian alps"
authors: Anne-Juul Welsink and Marrit Leenstra
date: 31 January 2019
output: html_notebook
---

TODO:
Project description

```{r}
# check if libraries are installed
if (!require("dplyr")) install.packages("dplyr")
if (!require("sp")) install.packages("sp")
if (!require("DBI")) install.packages("DBI")
if (!require("RSQLite")) install.packages("RSQLite")
if (!require("raster")) install.packages("raster")
```

```{r}
# load libraries
library(dplyr)
library(sp)
library(DBI)
library(raster)
```

```{r}
# import functions
source("R/retrieveData.R")
```

```{r}
# project variables
movementDataURL = "extras.springer.com/2014/978-3-319-03742-4/trackingDB_datasets.zip"
```

```{r}
# download movement data
folder = "data"
retrieveData(movementDataURL, folder)

# load libraries
library(sf)

# Source functions
source('R/retrieveData.R')

# create output folder if needed
if (!dir.exists("output")){
  dir.create("output")
}

# download and unzip data
url = "https://drive.google.com/uc?export=download&id=1vNgOAR-2HtXKpdfZTRsiJW4bMsHTbOjR"
retrieveData(url,"data")

fileList <- list.files(path = "data/GoogleEarthData", pattern = glob2rx('*.tif'), full.names = TRUE)
for (file in fileList){
  raster(file)
}
# Load data to global environment
DEM <- raster(fileList[1])
landUse <- raster(fileList[2])
slope <- raster(fileList[3])

```

```{r}
# load data to global environment
animalData <- read.csv2(file = "data/tracking_db/data/sensors_data/GSM01438.csv", header = TRUE)
animal2 <- read.csv2(file = "data/tracking_db/data/sensors_data/GSM01438.csv", header = TRUE)
```

```{r}
# create database (in memory)
movementDB <- dbConnect(RSQLite::SQLite(), "")
dbWriteTable(movementDB, "GPSData", animalData)
dbWriteTable(movementDB, "GPSData", animal2, append=TRUE)
```

```{r}
# use data
dbListTables(movementDB)
dbListFields(movementDB, "GPSData")
dbGetQuery(movementDB, 'SELECT "COLLAR_CODE.C.8", "LATITUDE.N.12.7", "LONGITUDE.N.12.7" FROM GPSDATA WHERE "COLLAR_CODE.C.8" = "GSM01438"')
```

```{r}
# disconnect database
dbDisconnect(movementDB)
```